### ISSUE TITLE
Not all LU events are synched/shown

### ISSUE THREAD

**Issue by Bolland** [codeuniversity/learning-platform-issues#7]
**Describe the bug**
It seems like not all events from my Learning Unit (PM_LU_38) are shown in the events platform "upcoming events" page. 

In the PM Guild Calendar, there are 12 events (until May 1), only 10 are shown in the events overview (until April 17th): https://app.code.berlin/event_groups/6261678439
  
After syncing a few times and updating the event in the cal, the events are not displayed.
The event group is added to all events.

**To Reproduce**
1. Check GUILD_PM Google Calendar (code.berlin_72gpt2s8d6tf2nearc5r14j42c@group.calendar.google.com) for the LU Event 
2. Head over to https://app.code.berlin/event_groups/6261678439 and compare amount of events

**Expected behavior**
I'd expect to see **all** future events at https://app.code.berlin/event_groups/6261678439 as it says upcoming. If they're capped after 10 (or at some point in the future), I'd expect a "show all", "next page" pagination option or something like (10 out of 20 total events shown)

**Screenshots**
![bildschirmfoto 2019-01-28 um 13 37 13](https://user-images.githubusercontent.com/1238151/51836828-dbbc4900-2301-11e9-94b3-d934727eaf1d.png)

**Desktop (please complete the following information):**
 - OS: X 10.13.6 (17G4015)
 - Browser: Chrome
- Version:  71.0.3578.98 (Offizieller Build) (64-Bit)

**Additional context**
A quick check revealed, that this seems to happen to other event groups with >10 events as well: https://app.code.berlin/event_groups/5693616925

**Comment by Bolland** [comment]
@luhagel  @robinboehm  did you guys see this?

**Comment by robinboehm** [comment]
Hey @Bolland,

Thanks for the great and detailed report! 
The events are synced but I limited the displayed number of "umcoming events" to 10 because some of the recurring events have ~50 "next events".

I totally agree with you and will think about a good way to show all events 👍

**Comment by Bolland** [comment]
Cool, thanks for clarifying, Robin! I was first confused, maybe a small
notice (upcoming events (max. 10)) would already solve the issue.
However, seeing all events would make sense for future planning.
